### ISSUE TITLE
week 01 作業回饋

### ISSUE THREAD

**Issue by azole** [gahwa17/git-practice#1]
現在的主分支是 master 嗎？
ps. visualizing-git 不錯，但就是舊了一點，一直沒有更新...

其他部分都做得不錯，是我期望整學期都可以維持的水準。

**Comment by gahwa17** [comment]
謝謝老師的回饋

1. 現在的主分支是 main
master 是 visualizing-git 中的範例

2. 後續找的互動式 git 教學網站 : [learnGitBranching](https://github.com/pcottle/learnGitBranching)，近期都還有在更新，好玩👍

**Comment by azole** [comment]
太好了，謝謝你的分享，我要收藏起來！

這個 issue 可以 close 了。

**Comment by gahwa17** [comment]
收到，謝謝老師~
